### PR TITLE
fix(rest): handle FastBuffer in toBlob

### PR DESCRIPTION
**Pull request by pharuxtan**
Buffer.from function create a "pooled" FastBuffer if the byteLength is under [`Buffer.poolSize`](https://nodejs.org/api/buffer.html#class-property-bufferpoolsize)` >>> 1` (which is equal to 4096 in default case).

This FastBuffer creation cause the buf.buffer ArrayBuffer to have a portion of the memory with the size of Buffer.poolSize (which is 8192 in default case) and not the real content of the Buffer.

This commit fix the rest `toBlob` utils function to handle these FastBuffer and return the correct data.

### CODE REVIEW

**Comment by paperdave** [comment]
checked this on my phone, seems good. I'm gonna take test this out later to make ensure it works and doesn't break anything.

**Comment by paperdave** [comment]
checked this on my phone, seems good. I'm gonna take test this out later to make ensure it works and doesn't break anything.

**Comment by paperdave** [comment]
while i did not mean to rewrite this implementation, i think it'd be simpler to just perform the logic you have to _all_ buffer objects and support the buffer object explicitly instead of implicitly

**Review by paperdave — DISMISSED** [review]

**Comment by pharuxtan** [comment]
I did this trick for performance. When a Uint8Array receive an ArrayBuffer or a TypedArray it will take his memory allocs without copying anything, but when he receive any other type of data that is iterable, it will iterate and copy all the content of the array-like object. By understanding this, the Uint8Array in the isFastBuffer actually don't convert and use the memory allocations of the ArrayBuffer sent, that make the compare very fast. But the Uint8Array on the toBlob actually create new mem allocs and copy the data. The thing that letting all Buffer goes on this Uint8Array convertion will make it 2 times slower, cause there is Buffer => Uint8Array, then ArrayBuffer => Blob, and not only ArrayBuffer => Blob if the Buffer is not pooled. This is confirmed by the perf test i did here https://imgur.com/a/XqixYXw

**Comment by paperdave** [comment]
what do you think of just using `return new Blob([data]);`, since i just learned that all Buffer/Uint8Array/ArrayBuffer objects seem to be convertable directly to a blob? I did a couple of minor tests and it seems to function across runtimes and run faster, since there's less work to be done.

**Comment by pharuxtan** [comment]
Go for that, seems good.

**Pull request merged**
