### PR TITLE
feat: add `@purplet/rest` to replace `@discordjs/rest`

### LINKED ISSUE #7: Our own rest client
working with `@discordjs/rest` is less than ideal, and glancing at it's code makes me feel like it's overcomplicated. I would like to have our own rest client, simply a set of functions that wrap fetch, implement rate limiting, errors, and (most important) provide typedefs for each known API route, because discord.js' doesn't do this for some reason.

if anyone wants to take this task up, I think a good name would be `@purplet/rest` (then a future `@purplet/gateway`), but the exact API I'm unsure of, maybe something like `rest.resourceName.actionName()` where these just mirror the discord api docs, such as `rest.channel.createMessage({ opts })` but also `rest.methodName(url, opts)`

### PR DESCRIPTION
**Pull request by davecaruso**
Closes #7 by implementing a rest client. Instead of explicitly relying on node.js or bun directly, we are using web standards and then `@purplet/polyfill` to add missing standards.

as it stands right now you need the polyfill for both runtimes: node <18 doesn't support fetch and formdata, and bun and node 18 have fetch but not formdata. this will probably get better in the future but idk how long that will be.

I also want to note this has modifications to `@purplet/polyfill` to get formdata working

### CODE REVIEW

**Comment by Hycord** [comment]
I'm bad at github, didn't mean to do that lmao

**Comment by davecaruso** [comment]
lmao nice. oh we'll shouldn't make anything different happen

**Comment by davecaruso** [comment]
last two commits implement files with form data. it's significant because the second commit changes the polyfill to mirror the web apis, so the implementation in rest is super simple.

**Comment by davecaruso** [comment]
`@purplet/rest` is published on the `next` dist-tag. we could get some testing with it. last step here is replacing rest client in purplet itself.

**Comment by davecaruso** [comment]
ready for code review.

**Review by Hycord — APPROVED** [review]
Needs to be tested before full 1.0.0 release
Otherwise, LGTM

**Pull request merged**
